name: Verify Migrations

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "migrations/**"
    

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: execute flyway in docker compose
        run: docker-compose up --abort-on-container-exit